### ISSUE TITLE
Conflicts with the "Forum" page of the "phpBB SiteMaker" extesion

### ISSUE THREAD

**Issue by demonlibra** [primehalo/primelinks#1]
Good day.
The are some conflict with "phpBB SiteMaker" extesion. On page "Forum" have this errors even if "Enable Link Processing:" set to "No".

`[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 547: include(): http:// wrapper is disabled in the server configuration by allow_url_include=0
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 547: include(http://localhost/forum/includes/utf/data/case_fold_c.php): failed to open stream: no suitable wrapper could be found
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 547: include(): Failed opening 'http://localhost/forum/includes/utf/data/case_fold_c.php' for inclusion (include_path='.:/opt/lampp/lib/php')
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 553: include(): http:// wrapper is disabled in the server configuration by allow_url_include=0
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 553: include(http://localhost/forum/includes/utf/data/case_fold_f.php): failed to open stream: no suitable wrapper could be found
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 553: include(): Failed opening 'http://localhost/forum/includes/utf/data/case_fold_f.php' for inclusion (include_path='.:/opt/lampp/lib/php')
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 563: strtr(): The second argument is not an array
[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 568: strtr(): The second argument is not an array
`

This problem only on page ".../app.php/forum".
Is it possible to disable extension "Prime Links" on that page?

Thanks

**Comment by primehalo** [comment]
Sorry for the delay. I just installed phpBB SiteMaker but I don't know how to replicate your issue. Can you talk me through it from the beginning?

**Comment by demonlibra** [comment]
Thank you for your time. I will try to describe as much as possible.

1. Install and Enable extension [phpBB SiteMaker 3.2.0](https://github.com/blitze/phpBB-ext-sitemaker/archive/release-3.2.0.zip)
2. Install and Enable extension [Pages](https://www.phpbb.com/customise/db/extension/pages/)
3. Open tab "Extension" -> "PAGES" -> "Manange pages" -> Create any empty page (eg **portal**)
[![pages.png](https://i.postimg.cc/DyJFxWqM/pages.png)](https://postimg.cc/dLYz1VN2)

4. Open this new page .../forum/app.php/**portal**
5. Click on a pencil in top right corner -> "SETTINGS" -> "Set as Start Page" -> "Exit Edit mode"
[![Set-As-Start-Page-1.png](https://i.postimg.cc/yxnP9YNh/Set-As-Start-Page-1.png)](https://postimg.cc/LgYLFSLh)
[![Set-As-Start-Page-2.png](https://i.postimg.cc/T2cQBQcy/Set-As-Start-Page-2.png)](https://postimg.cc/mhtQHYJR)

6. Reload page .../forum/app.php/**portal**
7. Click on link "Forum" (This virtual page replaced page index.php)
[![forum.png](https://i.postimg.cc/9Q29VjFC/forum.png)](https://postimg.cc/MvsHbNQF)

If "Prime links" is enable and try to open link "Forum" get many errors.
[![errors.png](https://i.postimg.cc/k56qp234/errors.png)](https://postimg.cc/Z9SG9Kqt)

**Comment by primehalo** [comment]
Okay, I don't believe this problem is actually caused by my extension, but rather the problem lies in the utf8_case_fold() function in the includes/utf/utf_tools.php file. You are only seeing these errors when my extension is installed because my extension calls that function. If you were to install any other extension which calls that function you would certainly be seeing the same errors.

The utf8_case_fold() function tries to include a file through the http protocol which isn't working. When I test it on my local system the first error I get is:
`[phpBB Debug] PHP Warning: in file [ROOT]/includes/utf/utf_tools.php on line 547: include(): http:// wrapper is disabled in the server configuration by allow_url_include=0`
And that is because in my php.ini I have `allow_url_include = Off`

Your error message is different though it could be due to the same cause. All the subsequent errors are likely caused by that first error so if you can fix the first error then the rest should go away. Check to see if your server configuration is set to allow URL includes.

**Comment by demonlibra** [comment]
php.ini already set  `allow_url_include = On` and I checked settings in tab `PHP information`
[![php.png](https://i.postimg.cc/R0m3mThK/php.png)](https://postimg.cc/w1WxcLhj)
Strange that with problem present only in one page.

Thank you.
I will try to find solution of the problem.

**Comment by primehalo** [comment]
I set it on mine also and then got this error:
`"failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error"`
I copied the URL that the error was showing inside the include() statement, pasted it into my browser, and it came back as a 500 Internal Server Error which explains why the include statement was not able to include it.

**Comment by primehalo** [comment]
There is an .htaccess file in the includes directory which is set to deny access. When I change that to allow access, most of those errors go away. The `strtr(): The second argument is not an array` errors still remain, though, as it seems the include statement is returning 1 instead of the array return value specified in the file. I don't know why.

**Comment by demonlibra** [comment]
I have the same situation.

**Comment by primehalo** [comment]
My guess is that this is a bug in the Pages extension, or maybe even in the forum itself, and my extension is just bringing it to light. I suppose it could also be a bug in the phpBB SiteMaker extension but I seriously doubt that

**Comment by primehalo** [comment]
I looked at this a little more. On a normal forum install the includes/utf_tools.php function utf8_case_fold() includes its files like so:
```
include('./includes/utf/data/case_fold_c.php');
include('./includes/utf/data/case_fold_f.php');
include('./includes/utf/data/case_fold_s.php');
```
The './' is supplied by the `$phpbb_root_path` variable, but when using phpBB SiteMaker that variable is the full http path of the forum. It looks like phpBB SiteMaker sets this variable inside blitze/sitemaker/controller/forum.php's handle() function:
`$phpbb_root_path = generate_board_url() . '/';`
I believe this is the root cause of the error. Above that line is a comment:
```
		/**
		 * This is ugly but the only way I could find
		 * to fix relative paths for forum images
		 */
```

So at least the author knows this was not the ideal way to fix his issue. I'd suggest letting the author know that doing this causes unintentional problems to spring up elsewhere.

---

BTW, I use the utf8_case_fold_nfc() function for comparing strings because it is what was recommended in the coding phpBB guidelines:
https://area51.phpbb.com/docs/30x/coding-guidelines.html

Under the Case Folding section.
